/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookmanagement;

/**
 *
 * @author x260
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pengunjung extends javax.swing.JFrame {

    /**
     * Creates new form Pengunjung
     */
    private Service service;
    private DefaultTableModel model;

    public Pengunjung() {
        initComponents();
        setLocationRelativeTo(null);

        // PAKAI SINGLETON (DATA TIDAK HILANG)
        service = Implemens.getInstance();

        // AMBIL MODEL DARI JTable YANG BENAR
        model = (DefaultTableModel) jTable1.getModel();
        loadDataBuku();
    }

    private void loadDataBuku() {
        model.setRowCount(0);
        for (Book b : service.getAllBooks()) {
            model.addRow(new Object[]{
                b.getIdBuku(),
                b.getJudul(),
                b.getPenulis(),
                b.getTahunTerbit()
            });
        }
    }

    private Book cariBuku(String input) {
        for (Book b : service.getAllBooks()) {
            if (b.getIdBuku().equalsIgnoreCase(input)
                    || b.getJudul().equalsIgnoreCase(input)) {
                return b;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtIdBuku = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        penulis = new javax.swing.JTextField();
        tahun1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pinjam = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamaPeminjam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNomorPeminjam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1003, 535));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBukuActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, -1));

        jLabel1.setText("ID Buku");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        jLabel2.setText("Judul");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel3.setText("Penulis");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 84, 20));

        penulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penulisActionPerformed(evt);
            }
        });
        jPanel2.add(penulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 200, -1));

        tahun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahun1ActionPerformed(evt);
            }
        });
        jPanel2.add(tahun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 200, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel5.setText("Masukan Data Anda");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        Pinjam.setText("Pinjam Buku");
        Pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinjamActionPerformed(evt);
            }
        });
        jPanel2.add(Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 290, -1));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel2.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 290, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel6.setText("Peminjaman Buku");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel4.setText("Nama Peminjam");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 20));

        txtNamaPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPeminjamActionPerformed(evt);
            }
        });
        jPanel2.add(txtNamaPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, -1));

        jLabel7.setText("Nomor Peminjam");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, 20));

        txtNomorPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomorPeminjamActionPerformed(evt);
            }
        });
        jPanel2.add(txtNomorPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 520));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Buku", "Judul Buku", "Penulis", "Tahun Terbit"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 660, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBukuActionPerformed

    private void penulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penulisActionPerformed

    private void tahun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahun1ActionPerformed

    private void PinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinjamActionPerformed
        // TODO add your handling code here:
        String inputBuku = txtIdBuku.getText().trim(); // bisa ID atau Judul
        String namaPeminjam = txtNamaPeminjam.getText().trim();
        String nomorPeminjam = txtNomorPeminjam.getText().trim();

        // 1. Validasi input
        if (inputBuku.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "ID Buku atau Judul Buku harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (namaPeminjam.isEmpty() || nomorPeminjam.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Nama dan Nomor Peminjam harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Cari buku
        Book buku = cariBuku(inputBuku);

        if (buku == null) {
            JOptionPane.showMessageDialog(this,
                    "Buku tidak ditemukan!",
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Jika berhasil
        JOptionPane.showMessageDialog(this,
                "Peminjaman Berhasil!\n\n"
                + "Judul Buku : " + buku.getJudul() + "\n"
                + "Peminjam   : " + namaPeminjam + "\n"
                + "Nomor      : " + nomorPeminjam,
                "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

        // 4. Optional: reset field
        txtIdBuku.setText("");
        txtNamaPeminjam.setText("");
        txtNomorPeminjam.setText("");
    }//GEN-LAST:event_PinjamActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        Login pengunjung = new Login();
        pengunjung.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void txtNamaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPeminjamActionPerformed

    private void txtNomorPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomorPeminjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField penulis;
    private javax.swing.JTextField tahun1;
    private javax.swing.JTextField txtIdBuku;
    private javax.swing.JTextField txtNamaPeminjam;
    private javax.swing.JTextField txtNomorPeminjam;
    // End of variables declaration//GEN-END:variables
}
